version: '2.1'

services:
  telegramnotifier:
    image: telegramnotifier
    build: .
    environment: 
      "NOTIFIER_TELEGRAM_TOKEN": "someToken"
      "NOTIFIER_TELEGRAM_FORWARDTO": "123"
      "NOTIFIER_TELEGRAM_DEBUG": "false"
      "NOTIFIER_HEALTHCHECK_DEBUG": "true"
      "NOTIFIER_HEALTHCHECK_HOSTS": "https://test.com/health/check"
    ports:
      - 8080:8080