name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build and publish the Docker image
      env:
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker build . --file Dockerfile --tag sergeylitvinov/telegram-notifier:$(date +%F) --tag sergeylitvinov/telegram-notifier:latest &&
        docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}} &&
        docker push sergeylitvinov/telegram-notifier:$(date +%F) &&
        docker push sergeylitvinov/telegram-notifier:latest &&
        docker logout      
